package com.miroslav.house.mapper;

import com.miroslav.house.model.HouseMsg;

public interface HouseMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_msg
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_msg
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    int insert(HouseMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_msg
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    int insertSelective(HouseMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_msg
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    HouseMsg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_msg
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    int updateByPrimaryKeySelective(HouseMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_msg
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    int updateByPrimaryKey(HouseMsg record);
}