package com.miroslav.house.mapper;

import com.miroslav.house.model.HouseUser;

public interface HouseUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    int insert(HouseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    int insertSelective(HouseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    HouseUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    int updateByPrimaryKeySelective(HouseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    int updateByPrimaryKey(HouseUser record);
}