package com.miroslav.house.model;

public class Community {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.id
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.city_code
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    private String cityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.city_name
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.name
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.id
     *
     * @return the value of community.id
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.id
     *
     * @param id the value for community.id
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.city_code
     *
     * @return the value of community.city_code
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.city_code
     *
     * @param cityCode the value for community.city_code
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.city_name
     *
     * @return the value of community.city_name
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.city_name
     *
     * @param cityName the value for community.city_name
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.name
     *
     * @return the value of community.name
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.name
     *
     * @param name the value for community.name
     *
     * @mbg.generated Tue Sep 25 14:35:20 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}